export const ATTRIBUTES = Object.freeze({
  typeset: "data-linebreak-typeset",
  line: "data-linebreak-line",
  fragment: "data-linebreak-fragment",
  fragmentStart: "data-linebreak-fragment-start",
  fragmentEnd: "data-linebreak-fragment-end",
  opportunity: "data-linebreak-opportunity",
  letterFit: "data-linebreak-letter-fit",
  wordFit: "data-linebreak-word-fit",
  authoredStyle: "data-linebreak-authored-style",
  atom: "data-linebreak-atom",
  decoration: "data-linebreak-decoration",
  decorationPosition: "data-linebreak-decoration-position",
  skip: "data-linebreak-skip",
  root: "data-linebreak-root",
})
