import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const source =
  "https://raw.githubusercontent.com/hyphenation/tex-hyphen/master/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-en-us.tex"
const sha256 =
  "f4ffcd96c5cbc886bdad23f95dcae8edc3cd3620eae62f7946eceda97c4e68f8"
const local = process.argv[2]
const text = local
  ? readFileSync(local, "utf8")
  : await (await fetch(source)).text()
if (createHash("sha256").update(text).digest("hex") !== sha256)
  throw new Error(
    "Hyphenation source checksum changed; review before regeneration",
  )
const clean = text.replace(/%[^\n]*/gu, "")
const entries = (command: string) =>
  [
    ...clean.matchAll(new RegExp(`\\\\${command}\\s*\\{([^}]*)\\}`, "gu")),
  ].flatMap((match) => match[1].trim().split(/\s+/u))
const patterns = entries("patterns").sort()
if (patterns.length !== 4938)
  throw new Error("Unexpected English pattern count")
let previous = ""
const packed = patterns
  .map((pattern) => {
    let shared = 0
    while (
      shared < Math.min(previous.length, pattern.length, 25) &&
      previous[shared] === pattern[shared]
    )
      shared += 1
    const suffix = pattern.slice(shared)
    if (/[A-Z]/u.test(suffix))
      throw new Error("Pattern suffix conflicts with marker alphabet")
    const token = String.fromCharCode(65 + shared) + suffix
    previous = pattern
    return token
  })
  .join("")
const header = `/**
 * Generated by scripts/generate-english-patterns.ts; do not edit by hand.
 * American English ushyphmax: all 4938 current dependency patterns, losslessly front-coded with uppercase prefix markers.
 * ${source}
 * Source SHA256: ${sha256}
 * Copyright (C) 1990, 2004, 2005 Gerard D.C. Kuiken.
 * Copying and distribution of this file, with or without modification,
 * are permitted in any medium without royalty provided the copyright
 * notice and this notice are preserved.
 * Includes Donald E. Knuth and Frank M. Liang's Plain TeX patterns.
 */\n`
writeFileSync(
  resolve(import.meta.dir, "../src/text/english-patterns.ts"),
  `${header}export const englishPatterns = ${JSON.stringify(packed)}\n\nexport const englishExceptions = ${JSON.stringify(entries("hyphenation").join(" "))}\n`,
)
console.log(
  `Generated ${patterns.length} English patterns (${packed.length} packed characters)`,
)
